version: '3.3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: 7ras0tresh/foodgram-project-react-backend
    depends_on: db
    env_file: .env
    volumes:
      - static:/static_backend
      - media:/media
    restart: always
  frontend:
    image: 7ras0tresh/foodgram-project-react-frontend
    depends_on: db
    volumes:
       - ../frontend/:/app/result_build/
  nginx:
    image: 7ras0tresh/kittygram_gateway
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
