# Generated by Django 3.2.3 on 2023-07-07 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        'Время приготовления не должно быть меньше 1')],
                verbose_name='Время приготовления'),
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'), name='unique_favourite'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'), name='already_in_the_list'),
        ),
    ]
