# Generated by Django 3.2.3 on 2023-07-07 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230707_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message='Время приготовления не должно быть меньше 1')],
                verbose_name='Время приготовления'),
        ),
    ]
